# Generated by Django 5.0.3 on 2024-03-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
